services:
  - type: web
    name: api
    env: docker
    plan: starter
    dockerfilePath: ./API/Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: postgres-db
          property: connectionString

      - key: ConnectionStrings__Redis
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

      - key: ASPNETCORE_URLS
        value: http://+:8080

      - key: ASPNETCORE_ENVIRONMENT
        value: Development

      - key: MAILGUN_API_KEY
        sync: false

      - key: Jwt__SecretKey
        sync: false

  - type: pserv
    name: postgres-db
    plan: starter
    postgresMajorVersion: 15

  - type: redis
    name: redis-cache
    plan: starter