services:
  - type: web
    name: api
    env: development
    plan: starter
    buildCommand: cd API && docker build -f Dockerfile -t api .
    startCommand: dotnet API.dll
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};
      - key: ConnectionStrings__Redis
        value: ${REDIS_HOST}:${REDIS_PORT}
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: MAILGUN_API_KEY
        value: ${MAILGUN_API_KEY}
      - key: Jwt__SecretKey
        value: ${Jwt__SecretKey}

  - type: postgresql
    name: postgres-db
    plan: starter
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: example
      - key: POSTGRES_DB
        value: mydb

  - type: redis
    name: redis-cache
    plan: starter
    envVars:
      - key: REDIS_PASSWORD
        value: ""